# Generated by Django 3.2.8 on 2021-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pd_proccessing_consent',
            field=models.NullBooleanField(verbose_name='Согласие на обработку ПД'),
        ),
    ]
