# Generated by Django 3.2.8 on 2021-10-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0002_auto_20211020_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tg_chat_id',
            field=models.PositiveIntegerField(db_index=True, default=1234567, unique=True, verbose_name='ID чата Телеграм'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=15, verbose_name='Телефон'),
        ),
    ]
