# Generated by Django 3.2.8 on 2021-10-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0007_auto_20211020_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', help_text='Используется только если добавлен параметр "Надпись на торте"', max_length=100, verbose_name='Надпись на торте')),
                ('is_in_order', models.BooleanField(blank=True, default=False, verbose_name='Добавлен в заказ?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='bake_cake_bot.client', verbose_name='Клиент, собравший торт')),
                ('options', models.ManyToManyField(db_index=True, related_name='used_in_cake', to='bake_cake_bot.Option', verbose_name='Параметры торта')),
            ],
        ),
    ]
