# Generated by Django 3.2.8 on 2021-10-21 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0008_cake'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена торта'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Заявка формируется'), (1, 'Заявка обрабатывается'), (2, 'Торт готовится'), (3, 'Торт в пути'), (4, 'Завершен')], default=0, verbose_name='Статус заказа')),
                ('total_amount', models.IntegerField(default=0, verbose_name='Сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения заказа')),
                ('cakes', models.ManyToManyField(related_name='in_orders', to='bake_cake_bot.Cake', verbose_name='Торты в заказе')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='bake_cake_bot.client', verbose_name='Клиент')),
            ],
        ),
    ]
