# Generated by Django 3.2.8 on 2021-10-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, default='', max_length=256, verbose_name='Адрес')),
                ('pd_proccessing_consent', models.NullBooleanField(verbose_name='Согласие на обработку персональных данных получено')),
            ],
        ),
    ]
