# Generated by Django 3.2.8 on 2021-10-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0003_auto_20211020_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pd_proccessing_consent',
            field=models.BooleanField(blank=True, null=True, verbose_name='Согласие на обработку ПД'),
        ),
    ]
