# Generated by Django 3.2.8 on 2021-10-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0006_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionCategory',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='option',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='bake_cake_bot.category', verbose_name='Категория'),
        ),
    ]
