# Generated by Django 3.2.8 on 2021-10-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bake_cake_bot', '0010_category_choice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='bake_cake_bot.client', verbose_name='Клиент'),
        ),
    ]
